#!/bin/bash
cd "$(dirname "$0")"
exec docker \
  run --rm \
  -e HOME="/home/coq" \
  -w "/work" \
  -v "${PWD}:/work" \
  -u "$(id -u):$(id -g)" \
  mathcomp/mathcomp:1.9.0-coq-8.9 \
  "./verify_all" "$@"
