#!/bin/bash
set -e

cd "$1"
shift
if [ ! -e "Makefile" ]; then
  coq_makefile -f "_CoqProject" -o "Makefile"
fi

lines="$(wc -l < Solution.v)"
bytes="$(wc -c < Solution.v)"
if make -C"${PWD}" "$@" > log 2>&1; then
  if ! grep 'Admitted\.' "Solution.v" > /dev/null 2>&1; then
    echo "0 PASS ${lines} ${bytes}" > status
  else
    echo "1 PENDING ${lines} ${bytes}" > status
  fi
else
  echo "2 FAIL ${lines} ${bytes}" > status
fi
